custom_components/tapo_control/camera.py, custom_components/tapo_control/manifest.json
Camera stream is now available even if user is not using "stream" integration
Handles a case when HASS requests camera image
=> Camera stream debug

README.md
I created this as a whole new section because I think there might be more various requirements in future.
=> [README] Add information on necessary open ports

custom_components/tapo_control/translations/pt_BR.json
Hello!
I just added a new json file into 'translations' folder. If any change is needed, please, tell me.
=> Brazilian Portuguese translation

custom_components/tapo_control/translations/zh-Hant.json
Hello! 
If any change is needed, please, tell me.
=> add Traditional Chinese translation

README.md
See https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/issues/243
=> Add C420S2 as not supported camera

custom_components/tapo_control/__init__.py, custom_components/tapo_control/button.py, custom_components/tapo_control/camera.py, custom_components/tapo_control/config_flow.py, custom_components/tapo_control/light.py, custom_components/tapo_control/manifest.json, custom_components/tapo_control/number.py, custom_components/tapo_control/select.py, custom_components/tapo_control/switch.py, custom_components/tapo_control/tapo/entities.py, custom_components/tapo_control/update.py, custom_components/tapo_control/utils.py
Adds support for cameras control through HUB, for example https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/issues/243
=> Add #243: Ability to add HUB

custom_components/tapo_control/media_source.py, custom_components/tapo_control/utils.py
- Fix: Unable to play a recording if path in .storage does not already exist
=> Beta 2: Media browser

custom_components/tapo_control/manifest.json, custom_components/tapo_control/media_source.py
- Fix: Incorrect time for recordings
- Fix: Crash on nonexistent file on md5 calculation
=> Beta 3: Media browser

custom_components/tapo_control/__init__.py, custom_components/tapo_control/manifest.json, custom_components/tapo_control/media_source.py, custom_components/tapo_control/utils.py
- Add: Siren entity by @ldotlopez
- Add: Warning about missing cloud password when trying to play recordings
=> 5.0.0.beta.4

custom_components/tapo_control/__init__.py
- Fix #289: TypeError: 'bool' object is not subscriptable
=> 5.0.0.beta.5

custom_components/tapo_control/__init__.py
- Fix #278: Integration causes a constant and abnormal increasing of CPU and RAM Memory usage
=> 5.0.0.beta.6

custom_components/tapo_control/binary_sensor.py
- Fix: AttributeError: 'NoneType' object has no attribute 'device_class' edge case
=> Fix: AttributeError: 'NoneType' object has no attribute 'device_class'

custom_components/tapo_control/manifest.json, custom_components/tapo_control/utils.py
- Fix #317: Recording Availible After an Hour
=> Fix #317: Recording Avalible After an Hour

custom_components/tapo_control/__init__.py, custom_components/tapo_control/sensor.py, custom_components/tapo_control/utils.py
- Better state for sensor
- Fix: Do not run findMedia until hass is started completely
- Fix: Unable to play recordings if using custom cold storage path
- Fix: Cleaner crashing on encountering unexpected file name
=> Sync media

custom_components/tapo_control/__init__.py
=> Fix/ Childs Name

custom_components/tapo_control/camera.py, custom_components/tapo_control/const.py, custom_components/tapo_control/manifest.json, custom_components/tapo_control/number.py, custom_components/tapo_control/select.py, custom_components/tapo_control/siren.py, custom_components/tapo_control/utils.py
Continuation of https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/pull/559
=> Pull 559 preparation

custom_components/tapo_control/number.py
=> Fix/ Duration and volume fix for hubs and c420s

custom_components/tapo_control/select.py
Changes on selection of entities to add to solve partially #637
=> Fix/ C420 automatic alarm and night mode

custom_components/tapo_control/utils.py
My D230 just got a firmware update, the quick response list looks different.
Therefore suggesting to implement this change, to check for the correct format.
Looks like the C520WS also has the "new" format, even though the feature is not supported there: https://github.com/JurajNyiri/pytapo/pull/133#issuecomment-2586716629
=> fix for firmware update of D230

README.md
As a new Home Assistant user, I found it difficult to locate the media configuration, so here is a suggestion for improving the readme.
=> Improvements to documentation of media configuration
