- examples/EXAMPLES_ENTITIES.md
Just two more examples with icon-template and friendly name like 
```yaml
bedroom_privacy_mode_switch:
friendly_name: Privacy Mode
value_template: [...]
turn_on: [...]
turn_off: [...]
icon_template: >-
{% if state_attr('camera.bedroom_hd', 'privacy_mode') == 'on' %}
mdi:eye-off-outline
{% else %}
mdi:eye-outline
{% endif %}
```
> Added two more template switches to the examples

- README.md
- custom_components/tapo_control/config_flow.py
- custom_components/tapo_control/manifest.json
- custom_components/tapo_control/strings.json
- custom_components/tapo_control/translations/en.json
- custom_components/tapo_control/utils.py
- hacs.json
This release enables discovery for Tapo cameras. 
This feature is now possible thanks to a newly added [DHCP Discovery](https://www.home-assistant.io/integrations/dhcp/) in Home Assistant.
You need to be using Home Assistant version 2021.2 or newer, and have DHCP integration enabled (or be using `default_config:`).
Your new camera will be automatically discovered when it (re)connects to wifi.
After your camera is discovered, you can configure it directly from Home Assistant Integration page.
- Automatic camera discovery
- Updated Troubleshooting / FAQ with more Q&A
- Config flow now does a lot more checks and informs user what he needs to do to resolve his issues. Following checks have been added:
- IP address is not a supported Tapo device
- Port 443, 554, or 2020 is closed
- IP address …
> Version 3.0 🔍

- custom_components/tapo_control/__init__.py
- custom_components/tapo_control/config_flow.py
- custom_components/tapo_control/const.py
- custom_components/tapo_control/strings.json
- custom_components/tapo_control/translations/en.json
- custom_components/tapo_control/utils.py
This release adds a possibility to synchronise time with your cameras. This is especially useful when your camera does not have internet access, because the time gets desynchronised fairly quickly.
You will need to enable this feature, by going to your integrations, finding your camera under Tapo integration and opening Options. There will be a new option to **Automatically synchronise time**.
After turning on this option, camera will now automatically synchronise time on Home Assistant start (or on camera being added) and then every 1 hour.
None.
> Version 3.1 🕐

- custom_components/tapo_control/__init__.py
- custom_components/tapo_control/camera.py
- custom_components/tapo_control/config_flow.py
- custom_components/tapo_control/const.py
- custom_components/tapo_control/manifest.json
- custom_components/tapo_control/strings.json
- custom_components/tapo_control/translations/en.json
- custom_components/tapo_control/translations/pt_BR.json
This release adds a support for noise detection as requested in https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/issues/71 .
You will need to enable this when adding the camera, or via options on existing cameras. When enabled, integration will analyse sound from camera stream in realtime and update a new attribute **noise_detected** to on, or off. This attribute is available only when noise detection is enabled and was initiated.
This expands possibilities of this camera, you could for example trigger an alarm based on noise or use the camera as baby monitor.
None.
> Version 3.3.0 🔊

- custom_components/tapo_control/camera.py
Fixes these kind of warnings beginning in 2021.12.0:
2021-12-13 21:02:03 WARNING (MainThread) [homeassistant.helpers.entity] Entity camera.outside_hd (<class 'custom_components.tapo_control.camera.TapoCamEntity'>) implements device_state_attributes. Please report it to the custom component author.
> Fix device_state_attributes warnings

- custom_components/tapo_control/binary_sensor.py
- custom_components/tapo_control/camera.py
- custom_components/tapo_control/update.py
By specifying the mac address inside the device info, HASS core can merge the Device with devices from other integrations, that are also the same camera. This could be, i.e. your router.
This fixes #170.
> specify mac address in device_info.connections #170

- custom_components/tapo_control/__init__.py
All entities should be unloaded or otherwise HASS core will become confused once the integration is being reloaded. HASS will refuse to reload both the binary_sensor and the update entity, which then breaks the integration.
This fixes #169.
> binary_sensor and update entities are never unloaded #169

- README.md
- custom_components/tapo_control/__init__.py
- custom_components/tapo_control/binary_sensor.py
- custom_components/tapo_control/camera.py
- custom_components/tapo_control/const.py
- custom_components/tapo_control/light.py
- custom_components/tapo_control/manifest.json
- custom_components/tapo_control/update.py
- custom_components/tapo_control/utils.py
Draft support for the C320WS floodlight.
- Adds DHCP mac address and hostname matcher
- Adds new light entity for the C320WS floodlight. Should only be added for Tapo cameras that support a floodlight switch.
- Slight refactor to reduce duplication DeviceInfo generation
- Also includes linting as applied by Home Assistant dev container
- Re-typed `tapoData` as a `dict`, as it is not a `Tapo` instance.
https://user-images.githubusercontent.com/1448441/167851478-5762873e-d48b-4c12-b65c-dc3f6131ca45.mp4
- This is my first publicly available Home Assistant integration work, and may be missing important things.
- Concerns about unloading. When unloading, the integration tries to unload the binary sensor, camera(s), update, and light, even if they were never added. This issue was present …
> Add C320WS floodlight

- custom_components/tapo_control/binary_sensor.py
- custom_components/tapo_control/camera.py
The integration provides sensors names which are prefixed with the camera name separated with a dash (`-`): `Flur -HD`, `Flur - Motion`
Within HA the camera name is trimmed again from the sensor name and it looks a bit odd like this:
Therefore I suggest to simply remove the `-`.
> fix(sensors): remove dash from sensor names

- custom_components/tapo_control/switch.py
I consider the "privacy mode" a general action and not a configuration setting.
> feat(config): list privacy mode under general controls instead of configuration

- custom_components/tapo_control/button.py
- custom_components/tapo_control/select.py
Changing the clock-like icon to an alarm-light for the manual alarm switches and the alarm select entity.
> feat(entity): change from clock icon to alarm-light icon

- hacs.json
Change `hacs.json` file to allow installation via HACS if running beta version of Home Assistant ([see example in HACS documentation here](https://hacs.xyz/docs/publish/start#hacsjson)).
> Allows use in the Home Assistant beta version

- custom_components/tapo_control/__init__.py
- custom_components/tapo_control/config_flow.py
- custom_components/tapo_control/manifest.json
- custom_components/tapo_control/strings.json
- custom_components/tapo_control/translations/en.json
- Fix #451: Some cameras after the latest firmware upgrade stick to their MD5 hash of cloud password instead of generating a new SHA256 resulting in failed authorization if trying with the new hash. Change introduced automatically detects the hashing algorithm and applies it. If camera changes the hashing algorithm, it will automatically detect a new one.
- Update: Re-authorization request now respects old firmwares and keeps cloud password optional
> Fix #451: Firmware 1.3.9: Incorrect Cloud credentials

- README.md
I installed the integration yesterday and couldn't get the cloud password to work despite following the troubleshooting steps mentioned in the various issues.
It turned out that 2-factor authentication was enabled on my Tapo account, which does not work with the integration.
This PR adds general instructions on what to try if the user encounters the error saying that the cloud password does not work. It includes the steps that are generally shared in the issues, but also adds the one to disable 2FA first.
> Added readme instructions for the cloud password not working

- custom_components/tapo_control/light.py
Reference:
https://developers.home-assistant.io/docs/core/entity/light#color-modes
> New integrations must implement both color_mode and supported_color_modes.
> If an integration is upgraded to support color mode, both color_mode and
> supported_color_modes should be implemented.
This also fixes this warning at startup:
```
WARNING (MainThread) [homeassistant.components.light] None (<class 'custom_components.tapo_control.light.TapoWhitelight'>) does not set supported color modes, this will stop working in Home Assistant Core 2025.3, please create a bug report at https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/issues
```
> Implement color mode (compatibility enhancement)

- custom_components/tapo_control/__init__.py
This handles cancelling the `mediaSync` event which continues every 60 seconds indefinitely even when an entry is removed.
It also removes the config entry data from hass when the entry is removed.
> Handle cleanup of config entry

- custom_components/tapo_control/utils.py
Changes on isCacheSupported and check_and_create,deferentiating missing functions from present but not supported, to avoid already made requests that are not supported. It improves load times significatively.
In the case of the hub several functions fall in this case like: `getPrivacyMode `, `getAlarm `, `getForceWhitelampState `, `getPresets `,  `getDayNightMode` and others.
> Charge times improvement - Not supported cached functions.

- custom_components/tapo_control/sensor.py
- custom_components/tapo_control/tapo/entities.py
The `state` property of a sensor entity is marked as final in Home Assistant code and should not be used for a sensor's state. Instead the recommendation is to use the `native_value` property. This switches the code to use `_attr_native_value` instead of `_attr_state` as well as some additional cleanup in the sensor.py file for readability.
See https://github.com/home-assistant/core/blob/dev/homeassistant/components/sensor/__init__.py#L538
and https://developers.home-assistant.io/docs/core/entity/sensor
> Use _attr_native_value instead of _attr_state in sensor entity

- custom_components/tapo_control/binary_sensor.py
- custom_components/tapo_control/button.py
- custom_components/tapo_control/camera.py
- custom_components/tapo_control/light.py
- custom_components/tapo_control/number.py
- custom_components/tapo_control/select.py
- custom_components/tapo_control/siren.py
- custom_components/tapo_control/switch.py
This `async_unload_entry` section of code is never called when unloading platforms, so this just cleans that up from the respective domains.
> Remove async_unload_entry code from platforms

- README.md
- custom_components/tapo_control/__init__.py
- custom_components/tapo_control/binary_sensor.py
- custom_components/tapo_control/config_flow.py
- custom_components/tapo_control/manifest.json
- custom_components/tapo_control/sensor.py
- custom_components/tapo_control/strings.json
- custom_components/tapo_control/switch.py
- custom_components/tapo_control/tapo/entities.py
- custom_components/tapo_control/translations/en.json
- custom_components/tapo_control/translations/ru.json
- custom_components/tapo_control/utils.py
- `binary_sensor.*_media_sync_enabled` entity is no longer present. It was replaced by `switch.*_media_sync` entity (along with extra attributes).
- Media Sync is no longer enabled or disabled via configuration of device, it is now instead controlled via entity `switch.*_media_sync`. Your current setting will be automatically migrated into this new entity.
- Even when `switch.*_media_sync` is enabled, you still need to define number of hours to synchronize via configuration of device in Home Assistant. See [readme](https://github.com/JurajNyiri/HomeAssistant-Tapo-Control?tab=readme-ov-file#media-sync) for more information.
> Add #667: Media Sync switch entity

- README.md
- custom_components/tapo_control/manifest.json
- custom_components/tapo_control/strings.json
- custom_components/tapo_control/translations/de.json
- custom_components/tapo_control/translations/en.json
- custom_components/tapo_control/translations/pt-BR.json
- custom_components/tapo_control/translations/ru.json
- custom_components/tapo_control/translations/zh-Hant.json
On **November 5, 2023**, I reported a security vulnerability to TP-Link. They addressed the issue, but by **April 2024**, users began reporting that their Tapo cameras had stopped working with this integration ([see issue](https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/issues/551#issue-2241778170)).  
Thankfully, a temporary workaround was discovered soon after: disabling the cameras' internet access and performing a factory reset restored full functionality.  
Then, on **May 8, 2024**, I was personally affected by this change. Motivated to find a lasting solution, I developed a [proof-of-concept (POC)](https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/issues/551#issuecomment-2111341474) just a week later. Within two days, the POC was polished and [ready for …
> Add: Instructions about Third Party Integration in official Tapo App

- custom_components/tapo_control/select.py
- custom_components/tapo_control/utils.py
This PR adds support for playing pre-recorded sounds on compatible devices (e.g., the D230 doorbell) by allowing users to select a sound for playback.
At this time, adding new sounds is only possible through the official Tapo app.
**Note: This functionality requires [https://github.com/JurajNyiri/pytapo/pull/133](https://github.com/JurajNyiri/pytapo/pull/133) to be accepted and merged, as it provides the required methods.**
> Add TapoQuickResponseSelect to handle quick response options

- custom_components/tapo_control/config_flow.py
Looks like a clear typo.
This prevents me from enabling motion sensor.
> Fix: incorrect check for RTSP enablement

- README.md
- custom_components/tapo_control/__init__.py
- custom_components/tapo_control/camera.py
- custom_components/tapo_control/config_flow.py
- custom_components/tapo_control/const.py
- custom_components/tapo_control/manifest.json
- custom_components/tapo_control/media_source.py
- custom_components/tapo_control/switch.py
- custom_components/tapo_control/utils.py
Integration now supports video stream through proprietary TP-Link protocol - called Direct stream. These Direct stream camera entities will automatically show up as enabled _HD (Direct)_ and _SD (Direct)_ (disabled by default), if RTSP streaming is not available for your camera.
If you have RTSP entities already, Direct entities will be disabled by default, but can be manually enabled.
1. **If you have a device which does not have RTSP functionality, you now have a stream in HA. This includes battery devices, solar devices, _as well as devices working through a hub_.** 🤯
2. If you have used up [all your RTSP streams](https://www.tp-link.com/cz/support/faq/2742/) and/or your RTSP streams are unstable in Home Assistant.
3. They are _extremely_ fast to load and have less than a half a second …
> Add #507: Stream, Downloads, Sync on devices without RTSP (hub included)
